#!/bin/sh

# v2ray main
v2ray=$(uci -q get v2ray.@v2ray[-1])
test -n "$v2ray" || uci -q add v2ray v2ray
if [ "x$v2ray" != "xmain" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@v2ray[-1]="main"
		set v2ray.main.enabled="0"
		commit v2ray
	EOF
fi

# dns
dns=$(uci -q get v2ray.@dns[-1])
test -n "$dns" || uci -q add v2ray dns
if [ "x$dns" != "xmain_dns" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@dns[-1]="main_dns"
		set v2ray.main_dns.enabled="0"
		commit v2ray
	EOF
fi

# routing
routing=$(uci -q get v2ray.@routing[-1])
test -n "$routing" || uci -q add v2ray routing
if [ "x$routing" != "xmain_routing" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@routing[-1]="main_routing"
		set v2ray.main_routing.enabled="0"
		commit v2ray
	EOF
fi

# policy
policy=$(uci -q get v2ray.@policy[-1])
test -n "$policy" || uci -q add v2ray policy
if [ "x$policy" != "xmain_policy" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@policy[-1]="main_policy"
		set v2ray.main_policy.enabled="0"
		commit v2ray
	EOF
fi

# reverse
reverse=$(uci -q get v2ray.@reverse[-1])
test -n "$reverse" || uci -q add v2ray reverse
if [ "x$reverse" != "xmain_reverse" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@reverse[-1]="main_reverse"
		set v2ray.main_reverse.enabled="0"
		commit v2ray
	EOF
fi

# transparent_proxy
transparent_proxy=$(uci -q get v2ray.@transparent_proxy[-1])
test -n "$transparent_proxy" || uci -q add v2ray transparent_proxy
if [ "x$transparent_proxy" != "xmain_transparent_proxy" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@reverse[-1]="main_transparent_proxy"
		set v2ray.main_transparent_proxy.redirect_port=""
		commit v2ray
	EOF
fi

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@v2ray[-1]
	add ucitrack v2ray
	set ucitrack.@v2ray[-1].init=v2ray
	commit ucitrack

	delete firewall.v2ray
	set firewall.v2ray=include
	set firewall.v2ray.type=script
	set firewall.v2ray.path=/etc/firewall.v2ray
	set firewall.v2ray.family=any
	set firewall.v2ray.reload=1
	commit firewall
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
