#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@v2ray[-1]
	add ucitrack v2ray
	set ucitrack.@v2ray[-1].init=v2ray
	commit ucitrack
EOF

v2ray=$(uci -q get v2ray.@v2ray[-1])
if [ -z "$v2ray" ] ; then
	uci -q add v2ray v2ray
fi
if [ "x$v2ray" != "xmain" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@v2ray[-1]="main"
		set v2ray.main.enabled="0"
		commit v2ray
	EOF
fi

dns=$(uci -q get v2ray.@dns[-1])
if [ -z "$dns" ] ; then
	uci -q add v2ray dns
fi
if [ "x$dns" != "xmain_dns" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@dns[-1]="main_dns"
		set v2ray.main_dns.enabled="0"
		commit v2ray
	EOF
fi

routing=$(uci -q get v2ray.@routing[-1])
if [ -z "$routing" ] ; then
	uci -q add v2ray routing
fi
if [ "x$routing" != "xmain_routing" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@routing[-1]="main_routing"
		set v2ray.main_routing.enabled="0"
		commit v2ray
	EOF
fi

policy=$(uci -q get v2ray.@policy[-1])
if [ -z "$policy" ] ; then
	uci -q add v2ray routing
fi
if [ "x$policy" != "xmain_policy" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@policy[-1]="main_policy"
		set v2ray.main_policy.enabled="0"
		commit v2ray
	EOF
fi

reverse=$(uci -q get v2ray.@reverse[-1])
if [ -z "$reverse" ] ; then
	uci -q add v2ray routing
fi
if [ "x$reverse" != "xmain_reverse" ] ; then
	uci -q batch <<-EOF >/dev/null
		rename v2ray.@reverse[-1]="main_reverse"
		set v2ray.main_reverse.enabled="0"
		commit v2ray
	EOF
fi

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
